const gridContainerBase = [
  "grid-cols-1",
  "grid-cols-2",
  "grid-cols-3",
  "grid-cols-4",
  "grid-cols-5",
  "grid-cols-6",
  "grid-cols-7",
  "grid-cols-8",
  "grid-cols-9",
  "grid-cols-10",
  "grid-cols-11",
  "grid-cols-12",
  "grid-cols-none",
] as const;

const gridRowsBase = [
  "grid-rows-1",
  "grid-rows-2",
  "grid-rows-3",
  "grid-rows-4",
  "grid-rows-5",
  "grid-rows-6",
  "grid-rows-none",
] as const;

const gridFlowBase = [
  "grid-flow-row",
  "grid-flow-col",
  "grid-flow-dense",
  "grid-flow-row-dense",
  "grid-flow-col-dense",
] as const;

const gridGapBase = [
  "gap-0",
  "gap-px",
  "gap-0.5",
  "gap-1",
  "gap-1.5",
  "gap-2",
  "gap-2.5",
  "gap-3",
  "gap-3.5",
  "gap-4",
  "gap-5",
  "gap-6",
  "gap-7",
  "gap-8",
  "gap-9",
  "gap-10",
  "gap-11",
  "gap-12",
  "gap-14",
  "gap-16",
  "gap-20",
  "gap-24",
  "gap-28",
  "gap-32",
  "gap-36",
  "gap-40",
  "gap-44",
  "gap-48",
  "gap-52",
  "gap-56",
  "gap-60",
  "gap-64",
  "gap-72",
  "gap-80",
  "gap-96",
] as const;

const gridGapXBase = [
  "gap-x-0",
  "gap-x-px",
  "gap-x-0.5",
  "gap-x-1",
  "gap-x-1.5",
  "gap-x-2",
  "gap-x-2.5",
  "gap-x-3",
  "gap-x-3.5",
  "gap-x-4",
  "gap-x-5",
  "gap-x-6",
  "gap-x-7",
  "gap-x-8",
  "gap-x-9",
  "gap-x-10",
  "gap-x-11",
  "gap-x-12",
  "gap-x-14",
  "gap-x-16",
  "gap-x-20",
  "gap-x-24",
  "gap-x-28",
  "gap-x-32",
  "gap-x-36",
  "gap-x-40",
  "gap-x-44",
  "gap-x-48",
  "gap-x-52",
  "gap-x-56",
  "gap-x-60",
  "gap-x-64",
  "gap-x-72",
  "gap-x-80",
  "gap-x-96",
] as const;

const gridGapYBase = [
  "gap-y-0",
  "gap-y-px",
  "gap-y-0.5",
  "gap-y-1",
  "gap-y-1.5",
  "gap-y-2",
  "gap-y-2.5",
  "gap-y-3",
  "gap-y-3.5",
  "gap-y-4",
  "gap-y-5",
  "gap-y-6",
  "gap-y-7",
  "gap-y-8",
  "gap-y-9",
  "gap-y-10",
  "gap-y-11",
  "gap-y-12",
  "gap-y-14",
  "gap-y-16",
  "gap-y-20",
  "gap-y-24",
  "gap-y-28",
  "gap-y-32",
  "gap-y-36",
  "gap-y-40",
  "gap-y-44",
  "gap-y-48",
  "gap-y-52",
  "gap-y-56",
  "gap-y-60",
  "gap-y-64",
  "gap-y-72",
  "gap-y-80",
  "gap-y-96",
] as const;

const gridJustifyItemsBase = [
  "justify-items-start",
  "justify-items-end",
  "justify-items-center",
  "justify-items-stretch",
] as const;

const gridAlignItemsBase = [
  "items-start",
  "items-end",
  "items-center",
  "items-stretch",
] as const;

const gridContainerSM = [
  "sm:grid-cols-1",
  "sm:grid-cols-2",
  "sm:grid-cols-3",
  "sm:grid-cols-4",
  "sm:grid-cols-5",
  "sm:grid-cols-6",
  "sm:grid-cols-7",
  "sm:grid-cols-8",
  "sm:grid-cols-9",
  "sm:grid-cols-10",
  "sm:grid-cols-11",
  "sm:grid-cols-12",
  "sm:grid-cols-none",
] as const;

const gridRowsSM = [
  "sm:grid-rows-1",
  "sm:grid-rows-2",
  "sm:grid-rows-3",
  "sm:grid-rows-4",
  "sm:grid-rows-5",
  "sm:grid-rows-6",
  "sm:grid-rows-none",
] as const;

const gridFlowSM = [
  "sm:grid-flow-row",
  "sm:grid-flow-col",
  "sm:grid-flow-dense",
  "sm:grid-flow-row-dense",
  "sm:grid-flow-col-dense",
] as const;

const gridGapSM = [
  "sm:gap-0",
  "sm:gap-px",
  "sm:gap-0.5",
  "sm:gap-1",
  "sm:gap-1.5",
  "sm:gap-2",
  "sm:gap-2.5",
  "sm:gap-3",
  "sm:gap-3.5",
  "sm:gap-4",
  "sm:gap-5",
  "sm:gap-6",
  "sm:gap-7",
  "sm:gap-8",
  "sm:gap-9",
  "sm:gap-10",
  "sm:gap-11",
  "sm:gap-12",
  "sm:gap-14",
  "sm:gap-16",
  "sm:gap-20",
  "sm:gap-24",
  "sm:gap-28",
  "sm:gap-32",
  "sm:gap-36",
  "sm:gap-40",
  "sm:gap-44",
  "sm:gap-48",
  "sm:gap-52",
  "sm:gap-56",
  "sm:gap-60",
  "sm:gap-64",
  "sm:gap-72",
  "sm:gap-80",
  "sm:gap-96",
] as const;

const gridGapXSM = [
  "sm:gap-x-0",
  "sm:gap-x-px",
  "sm:gap-x-0.5",
  "sm:gap-x-1",
  "sm:gap-x-1.5",
  "sm:gap-x-2",
  "sm:gap-x-2.5",
  "sm:gap-x-3",
  "sm:gap-x-3.5",
  "sm:gap-x-4",
  "sm:gap-x-5",
  "sm:gap-x-6",
  "sm:gap-x-7",
  "sm:gap-x-8",
  "sm:gap-x-9",
  "sm:gap-x-10",
  "sm:gap-x-11",
  "sm:gap-x-12",
  "sm:gap-x-14",
  "sm:gap-x-16",
  "sm:gap-x-20",
  "sm:gap-x-24",
  "sm:gap-x-28",
  "sm:gap-x-32",
  "sm:gap-x-36",
  "sm:gap-x-40",
  "sm:gap-x-44",
  "sm:gap-x-48",
  "sm:gap-x-52",
  "sm:gap-x-56",
  "sm:gap-x-60",
  "sm:gap-x-64",
  "sm:gap-x-72",
  "sm:gap-x-80",
  "sm:gap-x-96",
] as const;

const gridGapYSM = [
  "sm:gap-y-0",
  "sm:gap-y-px",
  "sm:gap-y-0.5",
  "sm:gap-y-1",
  "sm:gap-y-1.5",
  "sm:gap-y-2",
  "sm:gap-y-2.5",
  "sm:gap-y-3",
  "sm:gap-y-3.5",
  "sm:gap-y-4",
  "sm:gap-y-5",
  "sm:gap-y-6",
  "sm:gap-y-7",
  "sm:gap-y-8",
  "sm:gap-y-9",
  "sm:gap-y-10",
  "sm:gap-y-11",
  "sm:gap-y-12",
  "sm:gap-y-14",
  "sm:gap-y-16",
  "sm:gap-y-20",
  "sm:gap-y-24",
  "sm:gap-y-28",
  "sm:gap-y-32",
  "sm:gap-y-36",
  "sm:gap-y-40",
  "sm:gap-y-44",
  "sm:gap-y-48",
  "sm:gap-y-52",
  "sm:gap-y-56",
  "sm:gap-y-60",
  "sm:gap-y-64",
  "sm:gap-y-72",
  "sm:gap-y-80",
  "sm:gap-y-96",
] as const;

const gridJustifyItemsSM = [
  "sm:justify-items-start",
  "sm:justify-items-end",
  "sm:justify-items-center",
  "sm:justify-items-stretch",
] as const;

const gridAlignItemsSM = [
  "sm:items-start",
  "sm:items-end",
  "sm:items-center",
  "sm:items-stretch",
] as const;

const gridContainerMD = [
  "md:grid-cols-1",
  "md:grid-cols-2",
  "md:grid-cols-3",
  "md:grid-cols-4",
  "md:grid-cols-5",
  "md:grid-cols-6",
  "md:grid-cols-7",
  "md:grid-cols-8",
  "md:grid-cols-9",
  "md:grid-cols-10",
  "md:grid-cols-11",
  "md:grid-cols-12",
  "md:grid-cols-none",
] as const;

const gridRowsMD = [
  "md:grid-rows-1",
  "md:grid-rows-2",
  "md:grid-rows-3",
  "md:grid-rows-4",
  "md:grid-rows-5",
  "md:grid-rows-6",
  "md:grid-rows-none",
] as const;

const gridFlowMD = [
  "md:grid-flow-row",
  "md:grid-flow-col",
  "md:grid-flow-dense",
  "md:grid-flow-row-dense",
  "md:grid-flow-col-dense",
] as const;

const gridGapMD = [
  "md:gap-0",
  "md:gap-px",
  "md:gap-0.5",
  "md:gap-1",
  "md:gap-1.5",
  "md:gap-2",
  "md:gap-2.5",
  "md:gap-3",
  "md:gap-3.5",
  "md:gap-4",
  "md:gap-5",
  "md:gap-6",
  "md:gap-7",
  "md:gap-8",
  "md:gap-9",
  "md:gap-10",
  "md:gap-11",
  "md:gap-12",
  "md:gap-14",
  "md:gap-16",
  "md:gap-20",
  "md:gap-24",
  "md:gap-28",
  "md:gap-32",
  "md:gap-36",
  "md:gap-40",
  "md:gap-44",
  "md:gap-48",
  "md:gap-52",
  "md:gap-56",
  "md:gap-60",
  "md:gap-64",
  "md:gap-72",
  "md:gap-80",
  "md:gap-96",
] as const;

const gridGapXMD = [
  "md:gap-x-0",
  "md:gap-x-px",
  "md:gap-x-0.5",
  "md:gap-x-1",
  "md:gap-x-1.5",
  "md:gap-x-2",
  "md:gap-x-2.5",
  "md:gap-x-3",
  "md:gap-x-3.5",
  "md:gap-x-4",
  "md:gap-x-5",
  "md:gap-x-6",
  "md:gap-x-7",
  "md:gap-x-8",
  "md:gap-x-9",
  "md:gap-x-10",
  "md:gap-x-11",
  "md:gap-x-12",
  "md:gap-x-14",
  "md:gap-x-16",
  "md:gap-x-20",
  "md:gap-x-24",
  "md:gap-x-28",
  "md:gap-x-32",
  "md:gap-x-36",
  "md:gap-x-40",
  "md:gap-x-44",
  "md:gap-x-48",
  "md:gap-x-52",
  "md:gap-x-56",
  "md:gap-x-60",
  "md:gap-x-64",
  "md:gap-x-72",
  "md:gap-x-80",
  "md:gap-x-96",
] as const;

const gridGapYMD = [
  "md:gap-y-0",
  "md:gap-y-px",
  "md:gap-y-0.5",
  "md:gap-y-1",
  "md:gap-y-1.5",
  "md:gap-y-2",
  "md:gap-y-2.5",
  "md:gap-y-3",
  "md:gap-y-3.5",
  "md:gap-y-4",
  "md:gap-y-5",
  "md:gap-y-6",
  "md:gap-y-7",
  "md:gap-y-8",
  "md:gap-y-9",
  "md:gap-y-10",
  "md:gap-y-11",
  "md:gap-y-12",
  "md:gap-y-14",
  "md:gap-y-16",
  "md:gap-y-20",
  "md:gap-y-24",
  "md:gap-y-28",
  "md:gap-y-32",
  "md:gap-y-36",
  "md:gap-y-40",
  "md:gap-y-44",
  "md:gap-y-48",
  "md:gap-y-52",
  "md:gap-y-56",
  "md:gap-y-60",
  "md:gap-y-64",
  "md:gap-y-72",
  "md:gap-y-80",
  "md:gap-y-96",
] as const;

const gridJustifyItemsMD = [
  "md:justify-items-start",
  "md:justify-items-end",
  "md:justify-items-center",
  "md:justify-items-stretch",
] as const;

const gridAlignItemsMD = [
  "md:items-start",
  "md:items-end",
  "md:items-center",
  "md:items-stretch",
] as const;

const gridContainerLG = [
  "lg:grid-cols-1",
  "lg:grid-cols-2",
  "lg:grid-cols-3",
  "lg:grid-cols-4",
  "lg:grid-cols-5",
  "lg:grid-cols-6",
  "lg:grid-cols-7",
  "lg:grid-cols-8",
  "lg:grid-cols-9",
  "lg:grid-cols-10",
  "lg:grid-cols-11",
  "lg:grid-cols-12",
  "lg:grid-cols-none",
] as const;

const gridRowsLG = [
  "lg:grid-rows-1",
  "lg:grid-rows-2",
  "lg:grid-rows-3",
  "lg:grid-rows-4",
  "lg:grid-rows-5",
  "lg:grid-rows-6",
  "lg:grid-rows-none",
] as const;

const gridFlowLG = [
  "lg:grid-flow-row",
  "lg:grid-flow-col",
  "lg:grid-flow-dense",
  "lg:grid-flow-row-dense",
  "lg:grid-flow-col-dense",
] as const;

const gridGapLG = [
  "lg:gap-0",
  "lg:gap-px",
  "lg:gap-0.5",
  "lg:gap-1",
  "lg:gap-1.5",
  "lg:gap-2",
  "lg:gap-2.5",
  "lg:gap-3",
  "lg:gap-3.5",
  "lg:gap-4",
  "lg:gap-5",
  "lg:gap-6",
  "lg:gap-7",
  "lg:gap-8",
  "lg:gap-9",
  "lg:gap-10",
  "lg:gap-11",
  "lg:gap-12",
  "lg:gap-14",
  "lg:gap-16",
  "lg:gap-20",
  "lg:gap-24",
  "lg:gap-28",
  "lg:gap-32",
  "lg:gap-36",
  "lg:gap-40",
  "lg:gap-44",
  "lg:gap-48",
  "lg:gap-52",
  "lg:gap-56",
  "lg:gap-60",
  "lg:gap-64",
  "lg:gap-72",
  "lg:gap-80",
  "lg:gap-96",
] as const;

const gridGapXLG = [
  "lg:gap-x-0",
  "lg:gap-x-px",
  "lg:gap-x-0.5",
  "lg:gap-x-1",
  "lg:gap-x-1.5",
  "lg:gap-x-2",
  "lg:gap-x-2.5",
  "lg:gap-x-3",
  "lg:gap-x-3.5",
  "lg:gap-x-4",
  "lg:gap-x-5",
  "lg:gap-x-6",
  "lg:gap-x-7",
  "lg:gap-x-8",
  "lg:gap-x-9",
  "lg:gap-x-10",
  "lg:gap-x-11",
  "lg:gap-x-12",
  "lg:gap-x-14",
  "lg:gap-x-16",
  "lg:gap-x-20",
  "lg:gap-x-24",
  "lg:gap-x-28",
  "lg:gap-x-32",
  "lg:gap-x-36",
  "lg:gap-x-40",
  "lg:gap-x-44",
  "lg:gap-x-48",
  "lg:gap-x-52",
  "lg:gap-x-56",
  "lg:gap-x-60",
  "lg:gap-x-64",
  "lg:gap-x-72",
  "lg:gap-x-80",
  "lg:gap-x-96",
] as const;

const gridGapYLG = [
  "lg:gap-y-0",
  "lg:gap-y-px",
  "lg:gap-y-0.5",
  "lg:gap-y-1",
  "lg:gap-y-1.5",
  "lg:gap-y-2",
  "lg:gap-y-2.5",
  "lg:gap-y-3",
  "lg:gap-y-3.5",
  "lg:gap-y-4",
  "lg:gap-y-5",
  "lg:gap-y-6",
  "lg:gap-y-7",
  "lg:gap-y-8",
  "lg:gap-y-9",
  "lg:gap-y-10",
  "lg:gap-y-11",
  "lg:gap-y-12",
  "lg:gap-y-14",
  "lg:gap-y-16",
  "lg:gap-y-20",
  "lg:gap-y-24",
  "lg:gap-y-28",
  "lg:gap-y-32",
  "lg:gap-y-36",
  "lg:gap-y-40",
  "lg:gap-y-44",
  "lg:gap-y-48",
  "lg:gap-y-52",
  "lg:gap-y-56",
  "lg:gap-y-60",
  "lg:gap-y-64",
  "lg:gap-y-72",
  "lg:gap-y-80",
  "lg:gap-y-96",
] as const;

const gridJustifyItemsLG = [
  "lg:justify-items-start",
  "lg:justify-items-end",
  "lg:justify-items-center",
  "lg:justify-items-stretch",
] as const;

const gridAlignItemsLG = [
  "lg:items-start",
  "lg:items-end",
  "lg:items-center",
  "lg:items-stretch",
] as const;

const gridContainerXL = [
  "xl:grid-cols-1",
  "xl:grid-cols-2",
  "xl:grid-cols-3",
  "xl:grid-cols-4",
  "xl:grid-cols-5",
  "xl:grid-cols-6",
  "xl:grid-cols-7",
  "xl:grid-cols-8",
  "xl:grid-cols-9",
  "xl:grid-cols-10",
  "xl:grid-cols-11",
  "xl:grid-cols-12",
  "xl:grid-cols-none",
] as const;

const gridRowsXL = [
  "xl:grid-rows-1",
  "xl:grid-rows-2",
  "xl:grid-rows-3",
  "xl:grid-rows-4",
  "xl:grid-rows-5",
  "xl:grid-rows-6",
  "xl:grid-rows-none",
] as const;

const gridFlowXL = [
  "xl:grid-flow-row",
  "xl:grid-flow-col",
  "xl:grid-flow-dense",
  "xl:grid-flow-row-dense",
  "xl:grid-flow-col-dense",
] as const;

const gridGapXL = [
  "xl:gap-0",
  "xl:gap-px",
  "xl:gap-0.5",
  "xl:gap-1",
  "xl:gap-1.5",
  "xl:gap-2",
  "xl:gap-2.5",
  "xl:gap-3",
  "xl:gap-3.5",
  "xl:gap-4",
  "xl:gap-5",
  "xl:gap-6",
  "xl:gap-7",
  "xl:gap-8",
  "xl:gap-9",
  "xl:gap-10",
  "xl:gap-11",
  "xl:gap-12",
  "xl:gap-14",
  "xl:gap-16",
  "xl:gap-20",
  "xl:gap-24",
  "xl:gap-28",
  "xl:gap-32",
  "xl:gap-36",
  "xl:gap-40",
  "xl:gap-44",
  "xl:gap-48",
  "xl:gap-52",
  "xl:gap-56",
  "xl:gap-60",
  "xl:gap-64",
  "xl:gap-72",
  "xl:gap-80",
  "xl:gap-96",
] as const;

const gridGapXXL = [
  "xl:gap-x-0",
  "xl:gap-x-px",
  "xl:gap-x-0.5",
  "xl:gap-x-1",
  "xl:gap-x-1.5",
  "xl:gap-x-2",
  "xl:gap-x-2.5",
  "xl:gap-x-3",
  "xl:gap-x-3.5",
  "xl:gap-x-4",
  "xl:gap-x-5",
  "xl:gap-x-6",
  "xl:gap-x-7",
  "xl:gap-x-8",
  "xl:gap-x-9",
  "xl:gap-x-10",
  "xl:gap-x-11",
  "xl:gap-x-12",
  "xl:gap-x-14",
  "xl:gap-x-16",
  "xl:gap-x-20",
  "xl:gap-x-24",
  "xl:gap-x-28",
  "xl:gap-x-32",
  "xl:gap-x-36",
  "xl:gap-x-40",
  "xl:gap-x-44",
  "xl:gap-x-48",
  "xl:gap-x-52",
  "xl:gap-x-56",
  "xl:gap-x-60",
  "xl:gap-x-64",
  "xl:gap-x-72",
  "xl:gap-x-80",
  "xl:gap-x-96",
] as const;

const gridGapYXL = [
  "xl:gap-y-0",
  "xl:gap-y-px",
  "xl:gap-y-0.5",
  "xl:gap-y-1",
  "xl:gap-y-1.5",
  "xl:gap-y-2",
  "xl:gap-y-2.5",
  "xl:gap-y-3",
  "xl:gap-y-3.5",
  "xl:gap-y-4",
  "xl:gap-y-5",
  "xl:gap-y-6",
  "xl:gap-y-7",
  "xl:gap-y-8",
  "xl:gap-y-9",
  "xl:gap-y-10",
  "xl:gap-y-11",
  "xl:gap-y-12",
  "xl:gap-y-14",
  "xl:gap-y-16",
  "xl:gap-y-20",
  "xl:gap-y-24",
  "xl:gap-y-28",
  "xl:gap-y-32",
  "xl:gap-y-36",
  "xl:gap-y-40",
  "xl:gap-y-44",
  "xl:gap-y-48",
  "xl:gap-y-52",
  "xl:gap-y-56",
  "xl:gap-y-60",
  "xl:gap-y-64",
  "xl:gap-y-72",
  "xl:gap-y-80",
  "xl:gap-y-96",
] as const;

const gridJustifyItemsXL = [
  "xl:justify-items-start",
  "xl:justify-items-end",
  "xl:justify-items-center",
  "xl:justify-items-stretch",
] as const;

const gridAlignItemsXL = [
  "xl:items-start",
  "xl:items-end",
  "xl:items-center",
  "xl:items-stretch",
] as const;

const gridContainer2XL = [
  "2xl:grid-cols-1",
  "2xl:grid-cols-2",
  "2xl:grid-cols-3",
  "2xl:grid-cols-4",
  "2xl:grid-cols-5",
  "2xl:grid-cols-6",
  "2xl:grid-cols-7",
  "2xl:grid-cols-8",
  "2xl:grid-cols-9",
  "2xl:grid-cols-10",
  "2xl:grid-cols-11",
  "2xl:grid-cols-12",
  "2xl:grid-cols-none",
] as const;

const gridRows2XL = [
  "2xl:grid-rows-1",
  "2xl:grid-rows-2",
  "2xl:grid-rows-3",
  "2xl:grid-rows-4",
  "2xl:grid-rows-5",
  "2xl:grid-rows-6",
  "2xl:grid-rows-none",
] as const;

const gridFlow2XL = [
  "2xl:grid-flow-row",
  "2xl:grid-flow-col",
  "2xl:grid-flow-dense",
  "2xl:grid-flow-row-dense",
  "2xl:grid-flow-col-dense",
] as const;

const gridGap2XL = [
  "2xl:gap-0",
  "2xl:gap-px",
  "2xl:gap-0.5",
  "2xl:gap-1",
  "2xl:gap-1.5",
  "2xl:gap-2",
  "2xl:gap-2.5",
  "2xl:gap-3",
  "2xl:gap-3.5",
  "2xl:gap-4",
  "2xl:gap-5",
  "2xl:gap-6",
  "2xl:gap-7",
  "2xl:gap-8",
  "2xl:gap-9",
  "2xl:gap-10",
  "2xl:gap-11",
  "2xl:gap-12",
  "2xl:gap-14",
  "2xl:gap-16",
  "2xl:gap-20",
  "2xl:gap-24",
  "2xl:gap-28",
  "2xl:gap-32",
  "2xl:gap-36",
  "2xl:gap-40",
  "2xl:gap-44",
  "2xl:gap-48",
  "2xl:gap-52",
  "2xl:gap-56",
  "2xl:gap-60",
  "2xl:gap-64",
  "2xl:gap-72",
  "2xl:gap-80",
  "2xl:gap-96",
] as const;

const gridGapX2XL = [
  "2xl:gap-x-0",
  "2xl:gap-x-px",
  "2xl:gap-x-0.5",
  "2xl:gap-x-1",
  "2xl:gap-x-1.5",
  "2xl:gap-x-2",
  "2xl:gap-x-2.5",
  "2xl:gap-x-3",
  "2xl:gap-x-3.5",
  "2xl:gap-x-4",
  "2xl:gap-x-5",
  "2xl:gap-x-6",
  "2xl:gap-x-7",
  "2xl:gap-x-8",
  "2xl:gap-x-9",
  "2xl:gap-x-10",
  "2xl:gap-x-11",
  "2xl:gap-x-12",
  "2xl:gap-x-14",
  "2xl:gap-x-16",
  "2xl:gap-x-20",
  "2xl:gap-x-24",
  "2xl:gap-x-28",
  "2xl:gap-x-32",
  "2xl:gap-x-36",
  "2xl:gap-x-40",
  "2xl:gap-x-44",
  "2xl:gap-x-48",
  "2xl:gap-x-52",
  "2xl:gap-x-56",
  "2xl:gap-x-60",
  "2xl:gap-x-64",
  "2xl:gap-x-72",
  "2xl:gap-x-80",
  "2xl:gap-x-96",
] as const;

const gridGapY2XL = [
  "2xl:gap-y-0",
  "2xl:gap-y-px",
  "2xl:gap-y-0.5",
  "2xl:gap-y-1",
  "2xl:gap-y-1.5",
  "2xl:gap-y-2",
  "2xl:gap-y-2.5",
  "2xl:gap-y-3",
  "2xl:gap-y-3.5",
  "2xl:gap-y-4",
  "2xl:gap-y-5",
  "2xl:gap-y-6",
  "2xl:gap-y-7",
  "2xl:gap-y-8",
  "2xl:gap-y-9",
  "2xl:gap-y-10",
  "2xl:gap-y-11",
  "2xl:gap-y-12",
  "2xl:gap-y-14",
  "2xl:gap-y-16",
  "2xl:gap-y-20",
  "2xl:gap-y-24",
  "2xl:gap-y-28",
  "2xl:gap-y-32",
  "2xl:gap-y-36",
  "2xl:gap-y-40",
  "2xl:gap-y-44",
  "2xl:gap-y-48",
  "2xl:gap-y-52",
  "2xl:gap-y-56",
  "2xl:gap-y-60",
  "2xl:gap-y-64",
  "2xl:gap-y-72",
  "2xl:gap-y-80",
  "2xl:gap-y-96",
] as const;

const gridJustifyItems2XL = [
  "2xl:justify-items-start",
  "2xl:justify-items-end",
  "2xl:justify-items-center",
  "2xl:justify-items-stretch",
] as const;

const gridAlignItems2XL = [
  "2xl:items-start",
  "2xl:items-end",
  "2xl:items-center",
  "2xl:items-stretch",
] as const;

const gridItemColSpanBase = [
  "col-span-1",
  "col-span-2",
  "col-span-3",
  "col-span-4",
  "col-span-5",
  "col-span-6",
  "col-span-7",
  "col-span-8",
  "col-span-9",
  "col-span-10",
  "col-span-11",
  "col-span-12",
  "col-span-full",
] as const;

const gridItemColStartBase = [
  "col-start-1",
  "col-start-2",
  "col-start-3",
  "col-start-4",
  "col-start-5",
  "col-start-6",
  "col-start-7",
  "col-start-8",
  "col-start-9",
  "col-start-10",
  "col-start-11",
  "col-start-12",
  "col-start-13",
  "col-start-auto",
] as const;

const gridItemColEndBase = [
  "col-end-1",
  "col-end-2",
  "col-end-3",
  "col-end-4",
  "col-end-5",
  "col-end-6",
  "col-end-7",
  "col-end-8",
  "col-end-9",
  "col-end-10",
  "col-end-11",
  "col-end-12",
  "col-end-13",
  "col-end-auto",
] as const;

const gridItemRowSpanBase = [
  "row-span-1",
  "row-span-2",
  "row-span-3",
  "row-span-4",
  "row-span-5",
  "row-span-6",
  "row-span-full",
] as const;

const gridItemRowStartBase = [
  "row-start-1",
  "row-start-2",
  "row-start-3",
  "row-start-4",
  "row-start-5",
  "row-start-6",
  "row-start-7",
  "row-start-auto",
] as const;

const gridItemRowEndBase = [
  "row-end-1",
  "row-end-2",
  "row-end-3",
  "row-end-4",
  "row-end-5",
  "row-end-6",
  "row-end-7",
  "row-end-auto",
] as const;

const gridItemJustifySelfBase = [
  "justify-self-auto",
  "justify-self-start",
  "justify-self-end",
  "justify-self-center",
  "justify-self-stretch",
] as const;

const gridItemAlignSelfBase = [
  "self-auto",
  "self-start",
  "self-end",
  "self-center",
  "self-stretch",
] as const;

const gridItemColSpanSM = [
  "sm:col-span-1",
  "sm:col-span-2",
  "sm:col-span-3",
  "sm:col-span-4",
  "sm:col-span-5",
  "sm:col-span-6",
  "sm:col-span-7",
  "sm:col-span-8",
  "sm:col-span-9",
  "sm:col-span-10",
  "sm:col-span-11",
  "sm:col-span-12",
  "sm:col-span-full",
] as const;

const gridItemColStartSM = [
  "sm:col-start-1",
  "sm:col-start-2",
  "sm:col-start-3",
  "sm:col-start-4",
  "sm:col-start-5",
  "sm:col-start-6",
  "sm:col-start-7",
  "sm:col-start-8",
  "sm:col-start-9",
  "sm:col-start-10",
  "sm:col-start-11",
  "sm:col-start-12",
  "sm:col-start-13",
  "sm:col-start-auto",
] as const;

const gridItemColEndSM = [
  "sm:col-end-1",
  "sm:col-end-2",
  "sm:col-end-3",
  "sm:col-end-4",
  "sm:col-end-5",
  "sm:col-end-6",
  "sm:col-end-7",
  "sm:col-end-8",
  "sm:col-end-9",
  "sm:col-end-10",
  "sm:col-end-11",
  "sm:col-end-12",
  "sm:col-end-13",
  "sm:col-end-auto",
] as const;

const gridItemRowSpanSM = [
  "sm:row-span-1",
  "sm:row-span-2",
  "sm:row-span-3",
  "sm:row-span-4",
  "sm:row-span-5",
  "sm:row-span-6",
  "sm:row-span-full",
] as const;

const gridItemRowStartSM = [
  "sm:row-start-1",
  "sm:row-start-2",
  "sm:row-start-3",
  "sm:row-start-4",
  "sm:row-start-5",
  "sm:row-start-6",
  "sm:row-start-7",
  "sm:row-start-auto",
] as const;

const gridItemRowEndSM = [
  "sm:row-end-1",
  "sm:row-end-2",
  "sm:row-end-3",
  "sm:row-end-4",
  "sm:row-end-5",
  "sm:row-end-6",
  "sm:row-end-7",
  "sm:row-end-auto",
] as const;

const gridItemJustifySelfSM = [
  "sm:justify-self-auto",
  "sm:justify-self-start",
  "sm:justify-self-end",
  "sm:justify-self-center",
  "sm:justify-self-stretch",
] as const;

const gridItemAlignSelfSM = [
  "sm:self-auto",
  "sm:self-start",
  "sm:self-end",
  "sm:self-center",
  "sm:self-stretch",
] as const;

const gridItemColSpanMD = [
  "md:col-span-1",
  "md:col-span-2",
  "md:col-span-3",
  "md:col-span-4",
  "md:col-span-5",
  "md:col-span-6",
  "md:col-span-7",
  "md:col-span-8",
  "md:col-span-9",
  "md:col-span-10",
  "md:col-span-11",
  "md:col-span-12",
  "md:col-span-full",
] as const;

const gridItemColStartMD = [
  "md:col-start-1",
  "md:col-start-2",
  "md:col-start-3",
  "md:col-start-4",
  "md:col-start-5",
  "md:col-start-6",
  "md:col-start-7",
  "md:col-start-8",
  "md:col-start-9",
  "md:col-start-10",
  "md:col-start-11",
  "md:col-start-12",
  "md:col-start-13",
  "md:col-start-auto",
] as const;

const gridItemColEndMD = [
  "md:col-end-1",
  "md:col-end-2",
  "md:col-end-3",
  "md:col-end-4",
  "md:col-end-5",
  "md:col-end-6",
  "md:col-end-7",
  "md:col-end-8",
  "md:col-end-9",
  "md:col-end-10",
  "md:col-end-11",
  "md:col-end-12",
  "md:col-end-13",
  "md:col-end-auto",
] as const;

const gridItemRowSpanMD = [
  "md:row-span-1",
  "md:row-span-2",
  "md:row-span-3",
  "md:row-span-4",
  "md:row-span-5",
  "md:row-span-6",
  "md:row-span-full",
] as const;

const gridItemRowStartMD = [
  "md:row-start-1",
  "md:row-start-2",
  "md:row-start-3",
  "md:row-start-4",
  "md:row-start-5",
  "md:row-start-6",
  "md:row-start-7",
  "md:row-start-auto",
] as const;

const gridItemRowEndMD = [
  "md:row-end-1",
  "md:row-end-2",
  "md:row-end-3",
  "md:row-end-4",
  "md:row-end-5",
  "md:row-end-6",
  "md:row-end-7",
  "md:row-end-auto",
] as const;

const gridItemJustifySelfMD = [
  "md:justify-self-auto",
  "md:justify-self-start",
  "md:justify-self-end",
  "md:justify-self-center",
  "md:justify-self-stretch",
] as const;

const gridItemAlignSelfMD = [
  "md:self-auto",
  "md:self-start",
  "md:self-end",
  "md:self-center",
  "md:self-stretch",
] as const;

const gridItemColSpanLG = [
  "lg:col-span-1",
  "lg:col-span-2",
  "lg:col-span-3",
  "lg:col-span-4",
  "lg:col-span-5",
  "lg:col-span-6",
  "lg:col-span-7",
  "lg:col-span-8",
  "lg:col-span-9",
  "lg:col-span-10",
  "lg:col-span-11",
  "lg:col-span-12",
  "lg:col-span-full",
] as const;

const gridItemColStartLG = [
  "lg:col-start-1",
  "lg:col-start-2",
  "lg:col-start-3",
  "lg:col-start-4",
  "lg:col-start-5",
  "lg:col-start-6",
  "lg:col-start-7",
  "lg:col-start-8",
  "lg:col-start-9",
  "lg:col-start-10",
  "lg:col-start-11",
  "lg:col-start-12",
  "lg:col-start-13",
  "lg:col-start-auto",
] as const;

const gridItemColEndLG = [
  "lg:col-end-1",
  "lg:col-end-2",
  "lg:col-end-3",
  "lg:col-end-4",
  "lg:col-end-5",
  "lg:col-end-6",
  "lg:col-end-7",
  "lg:col-end-8",
  "lg:col-end-9",
  "lg:col-end-10",
  "lg:col-end-11",
  "lg:col-end-12",
  "lg:col-end-13",
  "lg:col-end-auto",
] as const;

const gridItemRowSpanLG = [
  "lg:row-span-1",
  "lg:row-span-2",
  "lg:row-span-3",
  "lg:row-span-4",
  "lg:row-span-5",
  "lg:row-span-6",
  "lg:row-span-full",
] as const;

const gridItemRowStartLG = [
  "lg:row-start-1",
  "lg:row-start-2",
  "lg:row-start-3",
  "lg:row-start-4",
  "lg:row-start-5",
  "lg:row-start-6",
  "lg:row-start-7",
  "lg:row-start-auto",
] as const;

const gridItemRowEndLG = [
  "lg:row-end-1",
  "lg:row-end-2",
  "lg:row-end-3",
  "lg:row-end-4",
  "lg:row-end-5",
  "lg:row-end-6",
  "lg:row-end-7",
  "lg:row-end-auto",
] as const;

const gridItemJustifySelfLG = [
  "lg:justify-self-auto",
  "lg:justify-self-start",
  "lg:justify-self-end",
  "lg:justify-self-center",
  "lg:justify-self-stretch",
] as const;

const gridItemAlignSelfLG = [
  "lg:self-auto",
  "lg:self-start",
  "lg:self-end",
  "lg:self-center",
  "lg:self-stretch",
] as const;

const gridItemColSpanXL = [
  "xl:col-span-1",
  "xl:col-span-2",
  "xl:col-span-3",
  "xl:col-span-4",
  "xl:col-span-5",
  "xl:col-span-6",
  "xl:col-span-7",
  "xl:col-span-8",
  "xl:col-span-9",
  "xl:col-span-10",
  "xl:col-span-11",
  "xl:col-span-12",
  "xl:col-span-full",
] as const;

const gridItemColStartXL = [
  "xl:col-start-1",
  "xl:col-start-2",
  "xl:col-start-3",
  "xl:col-start-4",
  "xl:col-start-5",
  "xl:col-start-6",
  "xl:col-start-7",
  "xl:col-start-8",
  "xl:col-start-9",
  "xl:col-start-10",
  "xl:col-start-11",
  "xl:col-start-12",
  "xl:col-start-13",
  "xl:col-start-auto",
] as const;

const gridItemColEndXL = [
  "xl:col-end-1",
  "xl:col-end-2",
  "xl:col-end-3",
  "xl:col-end-4",
  "xl:col-end-5",
  "xl:col-end-6",
  "xl:col-end-7",
  "xl:col-end-8",
  "xl:col-end-9",
  "xl:col-end-10",
  "xl:col-end-11",
  "xl:col-end-12",
  "xl:col-end-13",
  "xl:col-end-auto",
] as const;

const gridItemRowSpanXL = [
  "xl:row-span-1",
  "xl:row-span-2",
  "xl:row-span-3",
  "xl:row-span-4",
  "xl:row-span-5",
  "xl:row-span-6",
  "xl:row-span-full",
] as const;

const gridItemRowStartXL = [
  "xl:row-start-1",
  "xl:row-start-2",
  "xl:row-start-3",
  "xl:row-start-4",
  "xl:row-start-5",
  "xl:row-start-6",
  "xl:row-start-7",
  "xl:row-start-auto",
] as const;

const gridItemRowEndXL = [
  "xl:row-end-1",
  "xl:row-end-2",
  "xl:row-end-3",
  "xl:row-end-4",
  "xl:row-end-5",
  "xl:row-end-6",
  "xl:row-end-7",
  "xl:row-end-auto",
] as const;

const gridItemJustifySelfXL = [
  "xl:justify-self-auto",
  "xl:justify-self-start",
  "xl:justify-self-end",
  "xl:justify-self-center",
  "xl:justify-self-stretch",
] as const;

const gridItemAlignSelfXL = [
  "xl:self-auto",
  "xl:self-start",
  "xl:self-end",
  "xl:self-center",
  "xl:self-stretch",
] as const;

const gridItemColSpan2XL = [
  "2xl:col-span-1",
  "2xl:col-span-2",
  "2xl:col-span-3",
  "2xl:col-span-4",
  "2xl:col-span-5",
  "2xl:col-span-6",
  "2xl:col-span-7",
  "2xl:col-span-8",
  "2xl:col-span-9",
  "2xl:col-span-10",
  "2xl:col-span-11",
  "2xl:col-span-12",
  "2xl:col-span-full",
] as const;

const gridItemColStart2XL = [
  "2xl:col-start-1",
  "2xl:col-start-2",
  "2xl:col-start-3",
  "2xl:col-start-4",
  "2xl:col-start-5",
  "2xl:col-start-6",
  "2xl:col-start-7",
  "2xl:col-start-8",
  "2xl:col-start-9",
  "2xl:col-start-10",
  "2xl:col-start-11",
  "2xl:col-start-12",
  "2xl:col-start-13",
  "2xl:col-start-auto",
] as const;

const gridItemColEnd2XL = [
  "2xl:col-end-1",
  "2xl:col-end-2",
  "2xl:col-end-3",
  "2xl:col-end-4",
  "2xl:col-end-5",
  "2xl:col-end-6",
  "2xl:col-end-7",
  "2xl:col-end-8",
  "2xl:col-end-9",
  "2xl:col-end-10",
  "2xl:col-end-11",
  "2xl:col-end-12",
  "2xl:col-end-13",
  "2xl:col-end-auto",
] as const;

const gridItemRowSpan2XL = [
  "2xl:row-span-1",
  "2xl:row-span-2",
  "2xl:row-span-3",
  "2xl:row-span-4",
  "2xl:row-span-5",
  "2xl:row-span-6",
  "2xl:row-span-full",
] as const;

const gridItemRowStart2XL = [
  "2xl:row-start-1",
  "2xl:row-start-2",
  "2xl:row-start-3",
  "2xl:row-start-4",
  "2xl:row-start-5",
  "2xl:row-start-6",
  "2xl:row-start-7",
  "2xl:row-start-auto",
] as const;

const gridItemRowEnd2XL = [
  "2xl:row-end-1",
  "2xl:row-end-2",
  "2xl:row-end-3",
  "2xl:row-end-4",
  "2xl:row-end-5",
  "2xl:row-end-6",
  "2xl:row-end-7",
  "2xl:row-end-auto",
] as const;

const gridItemJustifySelf2XL = [
  "2xl:justify-self-auto",
  "2xl:justify-self-start",
  "2xl:justify-self-end",
  "2xl:justify-self-center",
  "2xl:justify-self-stretch",
] as const;

const gridItemAlignSelf2XL = [
  "2xl:self-auto",
  "2xl:self-start",
  "2xl:self-end",
  "2xl:self-center",
  "2xl:self-stretch",
] as const;

const GRID_CLASS_SAFELIST = [
  ...gridContainerBase,
  gridRowsBase,
  gridFlowBase,
  gridGapBase,
  gridGapXBase,
  gridGapYBase,
  gridJustifyItemsBase,
  gridAlignItemsBase,
  gridContainerSM,
  gridRowsSM,
  gridFlowSM,
  gridGapSM,
  gridGapXSM,
  gridGapYSM,
  gridJustifyItemsSM,
  gridAlignItemsSM,
  gridContainerMD,
  gridRowsMD,
  gridFlowMD,
  gridGapMD,
  gridGapXMD,
  gridGapYMD,
  gridJustifyItemsMD,
  gridAlignItemsMD,
  gridContainerLG,
  gridRowsLG,
  gridFlowLG,
  gridGapLG,
  gridGapXLG,
  gridGapYLG,
  gridJustifyItemsLG,
  gridAlignItemsLG,
  gridContainerXL,
  gridRowsXL,
  gridFlowXL,
  gridGapXL,
  gridGapXXL,
  gridGapYXL,
  gridJustifyItemsXL,
  gridAlignItemsXL,
  gridContainer2XL,
  gridRows2XL,
  gridFlow2XL,
  gridGap2XL,
  gridGapX2XL,
  gridGapY2XL,
  gridJustifyItems2XL,
  gridAlignItems2XL,
  gridItemColSpanBase,
  gridItemColStartBase,
  gridItemColEndBase,
  gridItemRowSpanBase,
  gridItemRowStartBase,
  gridItemRowEndBase,
  gridItemJustifySelfBase,
  gridItemAlignSelfBase,
  gridItemColSpanSM,
  gridItemColStartSM,
  gridItemColEndSM,
  gridItemRowSpanSM,
  gridItemRowStartSM,
  gridItemRowEndSM,
  gridItemJustifySelfSM,
  gridItemAlignSelfSM,
  gridItemColSpanMD,
  gridItemColStartMD,
  gridItemColEndMD,
  gridItemRowSpanMD,
  gridItemRowStartMD,
  gridItemRowEndMD,
  gridItemJustifySelfMD,
  gridItemAlignSelfMD,
  gridItemColSpanLG,
  gridItemColStartLG,
  gridItemColEndLG,
  gridItemRowSpanLG,
  gridItemRowStartLG,
  gridItemRowEndLG,
  gridItemJustifySelfLG,
  gridItemAlignSelfLG,
  gridItemColSpanXL,
  gridItemColStartXL,
  gridItemColEndXL,
  gridItemRowSpanXL,
  gridItemRowStartXL,
  gridItemRowEndXL,
  gridItemJustifySelfXL,
  gridItemAlignSelfXL,
  gridItemColSpan2XL,
  gridItemColStart2XL,
  gridItemColEnd2XL,
  gridItemRowSpan2XL,
  gridItemRowStart2XL,
  gridItemRowEnd2XL,
  gridItemJustifySelf2XL,
  gridItemAlignSelf2XL,
] as const;

void GRID_CLASS_SAFELIST;
